# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: RoveCommTester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build with pyinstaller 
      run: |
        cd RoveComm_Tester
        pyinstaller -F --icon=rover_swoosh.ico RoveComm_Tester.py
    - name: set env
      run: |
         cd ..
         echo "RELEASE_NAME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Release Apps
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.RELEASE_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "/dist/RoveComm_Tester.exe"
